### PR TITLE
Completion of the issue #30 "create event page Main events section"

### PR DESCRIPTION
**Pull request by Navojith**
The issue https://github.com/ms-club-sliit/fcmu/issues/30 is completed among other things.

new:
1. merge conflict resolve
2. bug fixes

prev:
1. Main Events has been implemented
2. Upcoming Events component remodeled to cater Main Events as well, dynamically.
3. Header updated to depict the selected page
4. Latest Notices section had a glitch that overflows the container . As a result , components below the Latest Notices were overlapped and hidden behind it. I was able to fix this issue, but it needs more improvements. (Sliding effect is less than ideal)
5. Updated all the paginations according to the style in the figma.
6. And bug fixes

### CODE REVIEW

**Comment by uihalagedara** [comment]
Pls upload a screenshot of the implementation

**Comment by Navojith** [comment]
Header now shows the selected page 

Screenshot 2023-04-28 183707


Main events component implemented

Screenshot 2023-04-28 184806


Latest Notices glitch fixed 


Screenshot 2023-04-28 184433


upcoming events updated

Screenshot 2023-04-28 184352


all the paginations updated to match the style in figma

Screenshot 2023-04-28 184457

**Comment by Navojith** [comment]
latest notices glitching (pre fix) 

Screenshot 2023-04-28 185156


latest notices fix + resized to match figma

Screenshot 2023-04-28 184936

**Review by MadhushaPrasad — APPROVED** [review]

**Comment by MadhushaPrasad** [comment]
@Navojith Please fix conflicting files

**Pull request closed without merging**
