### PR TITLE
Contact us form done

### PR DESCRIPTION
**Pull request by IndudiniThennakoon**
@uihalagedara pls check the contact us form

image
image

### CODE REVIEW

**Comment by uihalagedara** [comment]
> @uihalagedara pls check the contact us form
> 
> image image

**Comment by uihalagedara** [comment]
Please upload the mobile view also

**Comment by IndudiniThennakoon** [comment]
> Please upload the mobile view also

sure aiya

**Review by senuravihanjayadeva — COMMENTED** [review]
I this just the UI

**Pull request merged**
